# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'Windows/Qt5', 'macOS/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'pim/akonadi' : '@same'
    'pim/akonadi-contacts' : '@same'
    'pim/grantleetheme' : '@same'
    'pim/kontactinterface' : '@same'
    'pim/kpimtextedit' : '@same'
    'pim/libkdepim' : '@same'
    'pim/pimcommon' : '@same'

- 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'macOS/Qt5']
  'require':
    'pim/akonadi-search' : '@same'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]
