# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows', 'macOS']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'pim/akonadi' : '@latest-kf6'
    'pim/akonadi-contacts' : '@latest-kf6'
    'pim/grantleetheme' : '@latest-kf6'
    'pim/kontactinterface' : '@latest-kf6'
    'pim/libkdepim' : '@latest-kf6'
    'pim/pimcommon' : '@latest-kf6'

- 'on': ['Linux', 'FreeBSD', 'macOS']
  'require':
    'pim/akonadi-search' : '@latest-kf6'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]
