# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'kde/pim/akonadi' : '@same'
    'kde/pim/akonadi-contacts' : '@same'
    'kde/pim/akonadi-search' : '@same'
    'kde/pim/grantleetheme' : '@same'
    'kde/pim/kontactinterface' : '@same'
    'kde/pim/kpimtextedit' : '@same'
    'kde/pim/libkdepim' : '@same'
    'kde/pim/libkleo' : '@same'
    'kde/pim/pimcommon' : '@same'
    'third-party/grantlee' : '@stable'
