{
    "KPlugin": {
        "Description": "Kontact KAddressBook Plugin",
        "Description[ca@valencia]": "Conector de la llibreta d'adreces de Kontact",
        "Description[ca]": "Connector de la llibreta d'adreces del Kontact",
        "Description[de]": "Adressbuch-Modul für Kontact",
        "Description[es]": "Complemento KAddressBook de Kontact",
        "Description[fr]": "Module externe « KAddressBook » de Kontact",
        "Description[it]": "Estensione per Kontact di KAddressbook",
        "Description[nl]": "Kontact KAddressBook-plug-in",
        "Description[pl]": "Wtyczka Kontact do współpracy z Książką Adresową",
        "Description[pt]": "'Plugin' de KAddressBook do Kontact",
        "Description[sk]": "Kontact KAddressBook Plugin",
        "Description[sl]": "Vtičnik Kontact adresar",
        "Description[sv]": "Kontact-insticksprogram för adressbok",
        "Description[tr]": "Kontact K Adres Defteri Eklentisi",
        "Description[uk]": "Додаток адресної книги Kontact",
        "Description[x-test]": "xxKontact KAddressBook Pluginxx",
        "EnabledByDefault": true,
        "Icon": "view-pim-contacts",
        "Id": "kontact_kaddressbookplugin",
        "License": "GPL",
        "Name": "Contacts",
        "Name[ca@valencia]": "Contactes",
        "Name[ca]": "Contactes",
        "Name[de]": "Kontakte",
        "Name[es]": "Contactos",
        "Name[fr]": "Recherche de contact « PIM »",
        "Name[it]": "Contatti",
        "Name[nl]": "Contactpersonen",
        "Name[pl]": "Kontakty",
        "Name[pt]": "Contactos",
        "Name[sk]": "Kontakty",
        "Name[sl]": "Contacts",
        "Name[sv]": "Kontakter",
        "Name[tr]": "Kişiler",
        "Name[uk]": "Контакти",
        "Name[x-test]": "xxContactsxx",
        "ServiceTypes": [
            "Kontact/Plugin",
            "KPluginInfo"
        ],
        "Version": "0.1"
    },
    "X-KDE-ConfigModuleNamespace": "pim@QT_MAJOR_VERSION@/kcms/kaddressbook/",
    "X-KDE-KontactPartExecutableName": "kaddressbook",
    "X-KDE-KontactPartLibraryName": "kaddressbookpart",
    "X-KDE-KontactPartLoadOnStart": false,
    "X-KDE-KontactPluginHasSummary": false,
    "X-KDE-KontactPluginVersion": 11,
    "X-KDE-Weight": "300"
}
