{
    "KPlugin": {
        "Description": "Kontact KAddressBook Plugin",
        "Description[az]": "Kontact KAddressBook qoşması",
        "Description[ca@valencia]": "Connector de la llibreta d'adreces de Kontact",
        "Description[ca]": "Connector de la llibreta d'adreces del Kontact",
        "Description[cs]": "Modul Knihy adres pro Kontact",
        "Description[de]": "Adressbuch-Modul für Kontact",
        "Description[en_GB]": "Kontact KAddressBook Plugin",
        "Description[es]": "Complemento KAddressBook de Kontact",
        "Description[eu]": "Kontact KAddressBook plugina",
        "Description[fi]": "Kontactin KAddressBook-liitännäinen",
        "Description[fr]": "Module externe « KAddressBook » de Kontact",
        "Description[ia]": "Plug-in pro Kontact KAddressBook",
        "Description[it]": "Estensione per Kontact di KAddressbook",
        "Description[ko]": "Kontact KAddressBook 플러그인",
        "Description[nl]": "Kontact KAddressBook-plug-in",
        "Description[pl]": "Wtyczka Kontact do współpracy z Książką Adresową",
        "Description[pt]": "'Plugin' de KAddressBook do Kontact",
        "Description[pt_BR]": "Plugin do KAddressBook para o Kontact",
        "Description[sk]": "Kontact KAddressBook Plugin",
        "Description[sl]": "Vtičnik Kontact adresar",
        "Description[sv]": "Kontact-insticksprogram för adressbok",
        "Description[tr]": "Kontact K Adres Defteri Eklentisi",
        "Description[uk]": "Додаток адресної книги Kontact",
        "Description[x-test]": "xxKontact KAddressBook Pluginxx",
        "EnabledByDefault": true,
        "Icon": "view-pim-contacts",
        "Id": "kontact_kaddressbookplugin",
        "License": "GPL",
        "Name": "Contacts",
        "Name[az]": "Əlaqələr",
        "Name[ca@valencia]": "Contactes",
        "Name[ca]": "Contactes",
        "Name[cs]": "Kontakty",
        "Name[de]": "Kontakte",
        "Name[en_GB]": "Contacts",
        "Name[es]": "Contactos",
        "Name[eu]": "Kontaktuak",
        "Name[fi]": "Yhteystiedot",
        "Name[fr]": "Recherche de contact « PIM »",
        "Name[ia]": "Contactos",
        "Name[it]": "Contatti",
        "Name[ko]": "연락처",
        "Name[nl]": "Contactpersonen",
        "Name[pl]": "Kontakty",
        "Name[pt]": "Contactos",
        "Name[pt_BR]": "Contatos",
        "Name[sk]": "Kontakty",
        "Name[sl]": "Contacts",
        "Name[sv]": "Kontakter",
        "Name[tr]": "Kişiler",
        "Name[uk]": "Контакти",
        "Name[x-test]": "xxContactsxx",
        "Version": "0.1"
    },
    "X-KDE-ConfigModuleNamespace": "pim@QT_MAJOR_VERSION@/kcms/kaddressbook/",
    "X-KDE-KontactPartExecutableName": "kaddressbook",
    "X-KDE-KontactPartLibraryName": "kaddressbookpart",
    "X-KDE-KontactPartLoadOnStart": false,
    "X-KDE-KontactPluginHasSummary": false,
    "X-KDE-KontactPluginVersion": 11,
    "X-KDE-Weight": "300"
}
